server:
  port: 9003

spring:
  application:
    name: dispatcher-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
    function:
      definition: pack|label # pipe (|) operator to compose function together in a data flow. Using (;) if you need define multiple function
    stream:
      bindings:
        packlabel-in-0: # input binding
          destination: order-accepted # actual name at the broker that the binder bind to
          group: ${spring.application.name}
        packlabel-out-0: # output binding
          destination: order-dispatched
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
