server:
  port: 9003

spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label # pipe (|) operator to compose function together in a data flow. Using (;) if you need define multiple function

