apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog-service # this selector will find all pods having label app: catalog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001

