name: Catalog Service Commit Stage

on:
  push:
    paths:
      - 'catalog-service/**'

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/common-ci.yaml
    with:
      service_dir: 'catalog-service'
      registry: 'ghcr.io'
      image_name: 'venkyvn/catalog-service'
      version: 'latest'

  package_and_publish:
    if: ${{ github.ref == 'refs/heads/master'}}
    needs: [build_and_test]
    uses: ./.github/workflows/common-ci.yaml
    with:
      service_dir: 'catalog-service'
      registry: 'ghcr.io'
      image_name: 'venkyvn/catalog-service'
      version: 'latest'
