name: Catalog Service Commit Stage

on:
  push:
    paths:
      - 'catalog-service/**'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  catalog-job:
    name: Catalog Job
    uses: ./.github/workflows/common-ci.yaml
    with:
      service_dir: 'catalog-service'
      registry: 'ghcr.io'
      image_name: 'venkyvn/catalog-service'
      version: 'latest'
