name: Common CI workflow

on:
  workflow_call:
    inputs:
      service_dir:
        description: "Directory of the service (e.g., 'order-service')"
        type: string
        required: true
      registry:
        description: "Container registry"
        type: string
        required: true
        default: "ghcr.io"
      image_name:
        type: string
        description: "Name of the container Image"
        required: true
      version:
        type: string
        description: "Image version"
        required: true
        default: "latest"

jobs:
  build_and_test:
    name: Build and test ${{ inputs.service_dir }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, unit tests and integration tests
        run: |
          cd ${{ inputs.service_dir }}
          chmod +x gradlew
          ./gradlew build
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
#      - name: Setup tools
#        uses: alexellis/setup-arkade@v3
#      - name: Install tools
#        uses: alexellis/arkade-get@master
#        with:
#          kubeconform: latest
#      - name: Validate Kubernetes manifests
#        run: |
#          kubeconform --strict {{ inputs.service_dir }}k8s

  package_and_publish:
    name: Package and publish ${{ inputs.service_dir }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build container image
        run: |
          cd ${{ inputs.service_dir }}
          chmod +x gradlew
          ./gradlew bootBuildImage \
            --imageName ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}
      - name: OCI image vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Log into container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run: docker push ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}
