name: Common CI workflow

on:
  workflow_call:
    inputs:
      service_dir:
        description: "Directory of the service (e.g., 'order-service')"
        type: string
        required: true
      registry:
        description: "Container registry"
        type: string
        required: true
        default: "ghcr.io"
      image_name:
        type: string
        description: "Name of the container Image"
        required: true
      version:
        type: string
        description: "Image version"
        required: true
        default: "latest"

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, unit tests and integration tests
        run: |
          cd ${{ inputs.service_dir }}
          chmod +x gradlew
          ./gradlew build
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
