name: Order Service Commit Stage

on:
  push:
    paths:
      - 'dispatcher-service/**'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  dispatcher-service-job:
    name: Dispatcher Service Job
    uses: ./.github/workflows/common-ci.yaml
    with:
      service_dir: 'dispatcher-service'
      registry: 'ghcr.io'
      image_name: 'venkyvn/dispatcher-service'
      version: 'latest'
