name: Order Service Commit Stage

on:
  push:
    paths:
      - 'edge-service/**'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  edge-service-job:
    name: Edge Service Job
    uses: ./.github/workflows/common-ci.yaml
    with:
      service_dir: 'edge-service'
      registry: 'ghcr.io'
      image_name: 'venkyvn/edge-service'
      version: 'latest'
